### ISSUE TITLE
Readme needs to be updated

### ISSUE THREAD

**Issue by mathiasi** [pjozsef/android-pipeline-library#1]
I just came across your library which seems pretty neat but it seems that the documentation is outdated.
I tried to import the DeviceLister however the class was removed at some point from what I can tell. The same goes for the deviceCountShouldBe command.

**Comment by pjozsef** [comment]
Hi, thanks for opening this issue.
Yes, those classes were removed, but the same functionality is available with steps.
I have updated the readme with the new steps, new arguments, new code snippets!
